on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Do build
      run: |
        echo "Building ..."
        sleep 3
        echo "Done!"

  deployStaging:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Staging"
      url: "https://staging.example.com"

    steps:
    - name: Download artifact from build job
      run: |
        echo "Downloading ..."
        sleep 1
        echo "Done!"

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      run: |
        echo "Deploying"
        sleep 3
        echo "Done"
        
  deployProduction:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: 
      - build
      - deployStaging
    environment:
      name: "Production"
      url: "https://prod.example.com"

    steps:
    - name: Download artifact from build job
      run: |
        echo "Downloading ..."
        sleep 1
        echo "Done!"

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      run: |
        echo "Deploying"
        sleep 3
        echo "Done"
